### ISSUE TITLE
[FEATURE] E#2-S#1 이미지 지도 구현

### ISSUE THREAD

**Issue by KimKwon** [TeamSodam/sodam-client#13]
## TASK 개요 

서울의 소품샵 지도 (이미지)를 구현해요.
각 행정구를 핸들링하기 쉽게 만들어볼 생각이에요.

## TODO 및 진행현황 

- [x] svg element 컴포넌트화
- [x] 각 행정구 영역/텍스트 그룹핑
- [x] 온클릭/호버 등 마우스 이벤트핸들러 부착
- [x] 온클릭 시 동작(카카오맵 나올 수 있도록) 플로우 러프하게 구현
