### ISSUE TITLE
[FEATURE] E#14-S#3,5 프로필 사진 수정/삭제, 테마 수정

### ISSUE THREAD

**Issue by sohee-K** [TeamSodam/sodam-client#148]
## 🌴 작업 브랜치 
`feature/mypage`

## 💼 TASK 개요 
마이페이지 프로필 사진을 수정하고 삭제할 수 있고, 테마를 수정할 수 있어요

## ✅ TODO 및 진행현황 

- [x] PUT/DELETE API 구현
- [x] 프로필 이미지 수정
- [x] 프로필 이미지 삭제
- [x] 테마 수정
