### ISSUE TITLE
[FEATURE] E#5-S#2 테마 카테고리 컴포넌트 구현

### ISSUE THREAD

**Issue by huiseon37** [TeamSodam/sodam-client#15]
## 🌴 작업 브랜치 

`feature/themeCategory`

## 💼 TASK 개요 
1. main 페이지에서 보이는 테마 카테고리 컴퓨넌트를 구현할 예정입니다
2. 테마별 소품샵 페이지에서도 테마 카테고리 컴포넌트를 재사용 할 수 있도록 구현할 예정입니다.

## ✅ TODO 및 진행현황 

- [x] main 페이지 기준으로 테마 카테고리 컴포넌트 생성
- [x] 테마별 소품샵 페이지에서 재사용 할 수 있도록 고려하여 컴포넌트 구현
- [x] 페이지 이동을 고려하여 컴포넌트 구현
