### ISSUE TITLE
[HOTFIX] 소품샵지도 관련

### ISSUE THREAD

**Issue by KimKwon** [TeamSodam/sodam-client#188]
## 🌴 작업 브랜치 

`hotfix/map`

## 💼 TASK 개요 

소품샵 지도 관련 QA를 수정해요.

## ✅ TODO 및 진행현황 

> 리스트업할 예정~

- [ ] 간단한 텍스트 or 간격 수정
  - [x] ‘로그인하고 내 취향의 소품샵 저장하러 가요.’ 해당 텍스트에서 온점을 느낌표로 변경 부탁드립니다 ㅎ,,ㅎ + "내 취향의" 줄바꿈
  - [x] 타이틀과 서브 타이틀 사이의 간격 넓히기
  - [x] 서브 타이틀 ‘~확인할 수 있어요’ 뒤에 온점 빼주세요
  - [x] 내가 저장한, 인기 순 텍스트/아이콘 크기(모바일, 태블릿) 
  - [x] 소품샵 툴팁: 카테고리가 줄바꿈될 경우 아예 밑줄로 내리기
  - [x] 소품샵 툴팁: 말풍선이 커질 경우 마커와 말풍선 사이 거리 조절  
  - [x] 지도 항상 중앙으로 오도록
