### ISSUE TITLE
[FEATURE] E#2-S#2,3 지도 UI 개선 & 데이터 API 설계

### ISSUE THREAD

**Issue by KimKwon** [TeamSodam/sodam-client#21]
## 🌴 작업 브랜치 

`feature/map_improve`

## 💼 TASK 개요 

mock-api를 활용해서 어떤 구를 클릭했을 때 해당 구에 해당하는 소품샵 정보가 나올 수 있도록 할 예정이에요.
또한 마커를 클릭했을 때 다른 말풍선들은 모두 보이지 않도록 하고 ... 마커와 커스텀 오버레이의 z-index를 조절해서 어색한 UI를 조절할 예정이에요!

## ✅ TODO 및 진행현황 

- [x] 행정구 클릭시 소품샵지도페이지에서 알맞는 데이터 fetch하도록 라이프사이클 설계
- [x] 더미데이터 제거 (mock-api 연결)
- [x] 기타 성능 개선
  - [x] 말풍선 z-index 관련 
  - [x] 말풍선 다중클릭 차단
