### ISSUE TITLE
[FEATURE] E#1-S#4 `카드 구현`

### ISSUE THREAD

**Issue by sohee-K** [TeamSodam/sodam-client#5]
## TASK 개요 
전체 뷰에서 공통적으로 사용되는 카드 컴포넌트 개발
- 리뷰 카드: 사진 + 사용자 이름 / 작성일 + 좋아요 및 스크랩 수 + 미리보기 + (hover 효과)
- 소품샵 카드: 사진 + 소품샵 이름 + 소품샵 분류 + (순위 깃발)

## TODO 및 진행현황 

- [x] 소품샵 정보 및 리뷰 Interface 작성
- [x] 리뷰 카드 기본 템플릿 개발
- [x] 리뷰 카드 분기처리(작성일 / hover 효과)
- [x] 소품샵 카드 기본 템플릿 개발
- [x] 소품샵 카드 분기처리(순위 깃발)
- [x] mock 데이터 넣어서 테스팅
