### ISSUE TITLE
[FEATURE] E#1-S#3 Redux 구조 세팅

### ISSUE THREAD

**Issue by KimKwon** [TeamSodam/sodam-client#6]
## TASK 개요 

1. RTK(Redux ToolKit) Query 구조를 세팅해요. (데이터 리패치, 캐싱 등을 이용해 `client-remote` 간 데이터 동기화)
2. API를 커스텀 훅을 통해 쉽게 가져오도록 해요. 

예상 결과물:
```javascript
const { date, isError, isLoading } = useGetShopList()
```

## TODO 및 진행현황 

- [x] RTK Query API endpoint 설계 (리뷰, 샵 정보 등)
- [x] RTK Query API 구현 
- [x] RTK Query API + axios
- [x] mock-api 작성 후 테스트
