### ISSUE TITLE
[FEATURE] E#9-S#4, E#10-S#1  추천 소품샵 , 오늘의 리뷰 API 연결

### ISSUE THREAD

**Issue by huiseon37** [TeamSodam/sodam-client#75]
## 🌴 작업 브랜치 
`feature/api-rcmdShop` `feature/api-review`

## 💼 TASK 개요 
추천 소품샵 API와 오늘의 리뷰 API를 연결할 예정입니다

## ✅ TODO 및 진행현황 

- [x] 추천 소품샵 API 연결
- [x] 오늘의 리뷰 API 연결
- [x] 데이터에 따른 뷰 구현
